server:
  port: 8080
  error:
    include-message: always
spring:
  datasource:
    url: 'jdbc:postgresql://localhost:59629/integration-tests-db?loggerLevel=OFF'
    username: 'admin'
    password: '@dm1n'
keycloak:
  auth-server-url: 'http://localhost:59749/'
  realm: vakantieplanner
  resource: spring-app
  use-resource-role-mappings: false
  bearer-only: true


