server:
  port: 8080
  error:
    include-message: always
spring:
  datasource:
    url: 'jdbc:postgresql://localhost:51248/standalone-db?loggerLevel=OFF'
    username: 'admin'
    password: 'admin'
keycloak:
  auth-server-url: 'http://localhost:51254/'
  realm: vakantieplanner
  resource: spring-app
  use-resource-role-mappings: false
  bearer-only: true


