/*
 * This file is generated by jOOQ.
 */
package nl.jnext.workshop.testcontainers.vakantieplanner.jooq;


import nl.jnext.workshop.testcontainers.vakantieplanner.jooq.tables.FlywaySchemaHistory;
import nl.jnext.workshop.testcontainers.vakantieplanner.jooq.tables.Holiday;
import nl.jnext.workshop.testcontainers.vakantieplanner.jooq.tables.Member;
import nl.jnext.workshop.testcontainers.vakantieplanner.jooq.tables.Team;
import nl.jnext.workshop.testcontainers.vakantieplanner.jooq.tables.records.FlywaySchemaHistoryRecord;
import nl.jnext.workshop.testcontainers.vakantieplanner.jooq.tables.records.HolidayRecord;
import nl.jnext.workshop.testcontainers.vakantieplanner.jooq.tables.records.MemberRecord;
import nl.jnext.workshop.testcontainers.vakantieplanner.jooq.tables.records.TeamRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("flyway_schema_history_pk"), new TableField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
    public static final UniqueKey<HolidayRecord> HOLIDAY_PKEY = Internal.createUniqueKey(Holiday.HOLIDAY, DSL.name("holiday_pkey"), new TableField[] { Holiday.HOLIDAY.ID }, true);
    public static final UniqueKey<MemberRecord> MEMBER_PKEY = Internal.createUniqueKey(Member.MEMBER, DSL.name("member_pkey"), new TableField[] { Member.MEMBER.ID }, true);
    public static final UniqueKey<TeamRecord> TEAM_PKEY = Internal.createUniqueKey(Team.TEAM, DSL.name("team_pkey"), new TableField[] { Team.TEAM.ID }, true);
}
