/*
 * This file is generated by jOOQ.
 */
package nl.jnext.workshop.testcontainers.vakantieplanner.jooq.tables.records;


import nl.jnext.workshop.testcontainers.vakantieplanner.jooq.tables.Member;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MemberRecord extends UpdatableRecordImpl<MemberRecord> implements Record3<Integer, Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.member.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.member.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.member.team_id</code>.
     */
    public void setTeamId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.member.team_id</code>.
     */
    public Integer getTeamId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.member.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.member.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, Integer, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Member.MEMBER.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Member.MEMBER.TEAM_ID;
    }

    @Override
    public Field<String> field3() {
        return Member.MEMBER.NAME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getTeamId();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getTeamId();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public MemberRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public MemberRecord value2(Integer value) {
        setTeamId(value);
        return this;
    }

    @Override
    public MemberRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public MemberRecord values(Integer value1, Integer value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MemberRecord
     */
    public MemberRecord() {
        super(Member.MEMBER);
    }

    /**
     * Create a detached, initialised MemberRecord
     */
    public MemberRecord(Integer id, Integer teamId, String name) {
        super(Member.MEMBER);

        setId(id);
        setTeamId(teamId);
        setName(name);
    }
}
